### ISSUE TITLE
error with pytorch 1.3.1

### ISSUE THREAD

**Issue by mariogeiger** [rwightman/gen-efficientnet-pytorch#15]
After updating pytorch 1.3.0 -> 1.3.1
I got the following error
```python
torch.hub.list('rwightman/gen-efficientnet-pytorch')
```
> `ImportError: cannot import name 'mobilenetv3_100' from 'geffnet' (/home/mario/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/__init__.py)`

**Comment by rwightman** [comment]
@mariogeiger I didn't update the hubconf with my latest changes, thanks
