### ISSUE TITLE
What's the difference between Efficientnet here and Efficientnet in pytorch-image-models

### ISSUE THREAD

**Issue by philip-bl** [rwightman/gen-efficientnet-pytorch#2]
Hello. I want to experiment with efficientnets - accelerate them further by replacing some convolution layers with other layers using trnsor decompositions. Is it better for me to use this repo or the other one? What is the difference between Efficientnet models in the two repos?

**Comment by rwightman** [comment]
Weights are exactly the same. Aside from splitting the model in two files, this stand alone version has less creation options, more typical torchvision like entrypoint fns and model interface assuming imagenet. The other one lets you choose different global pool, change FC layer easily, different input channels, etc.
