### ISSUE TITLE
[request] add prerequisites to the landing page

### ISSUE THREAD

**Issue by mattans** [rwightman/gen-efficientnet-pytorch#20]
Hi,
Could you add a prerequisites section to your landing page?
Specifying supported operating systems, Python versions. PyTorch versions, CUDA support etc.?

Thanks.

**Comment by rwightman** [comment]
I'll do this with next updates, it's currently been tested with PyTorch 1.2, 1.31, Conda based Python 3.6.x and 3.7.x installs. I have only run on Linux but I hear it should run on Windows fine.

**Comment by mk123qwe** [comment]
win10 , python3.6 & cuda10.1 is OK.
