### ISSUE TITLE
only want to use mobilenetv3 model

### ISSUE THREAD

**Issue by mk123qwe** [rwightman/gen-efficientnet-pytorch#24]
only want to use mobilenetv3 model，example mobilenetv3.py is only model，no creating model and load pretrain.Could you give me some advice?

**Comment by rwightman** [comment]
@mk123qwe sorry, I have no idea what you mean... the README shows examples how to instantiate models here, mobilenetv3 included. You can choose pretrained or no pretrained flag. You can move the geffnet folder into your own project, instlall from pip, or use via PyTorch Hub. If you want everything for just mobilenetv3 in one file you can do the reorganization yourself to achieve that...
