### ISSUE TITLE
'mobilenetv3_small_075': None,mobilenetv3_small_075 is still not available?

### ISSUE THREAD

**Issue by mk123qwe** [rwightman/gen-efficientnet-pytorch#27]
mobilenetv3_small_075 is still not available?

**Comment by rwightman** [comment]
I have not trained that model from scratch in PyTorch, the converted Tensorflow weights are available as  `tf_mobilenetv3_small_075` ... you are welcome to train it at make a contribution ... I have experiments runnign training mobilenetv3_small_100 but I don't know how they'll turn out yet
