### ISSUE TITLE
Unable to access to _SCRIPTABLE and _EXPORTABLE from torch.hub

### ISSUE THREAD

**Issue by foreverYoungGitHub** [rwightman/gen-efficientnet-pytorch#32]
Hi @rwightman!

Thank you for your great implementation for efficientnet and its relatives.

I found the global param is _SCRIPTABLE and _EXPORTABLE in the config file. However, when I use torch hub to access the model, it is hard for me to acces these two variables and successful export the model. In this case I'm wondering is that possible to set _SCRIPTABLE and _EXPORTABLE as a parameter of EfficientNetBuilder?

Best,

**Comment by rwightman** [comment]
Hmm, I'll think about how to do that cleanly, definitely an issue with the reduced interface you get via hub. Passing them all the way through the builder to the point where the layers are instantiated adds a lot of mess.

**Comment by foreverYoungGitHub** [comment]
Besides, after I converted to the tensorrt, the inference time and memory cost is pretty high. Just kind of curious about that. Is it caused by the swishes? Is there the only way to improve it is to wait the tensorrt to improve their backend?

To renference, the speed I tested for the ssd-mobilenet v1 and v2 with batch 16 is 23.12ms & 34.58ms. The speed for ssd-efficientnetb0 with batch 8 is 26.45ms.

**Comment by rwightman** [comment]
Yes, the Swish activation, and having an SE every block is fairly high cost for mobile/CPU inference. Not sure if Tensorrt has an optimal Swish impl yet? If it did, would likely require some annotation as there isn't one in native PyTorch.

If you check out my BENCHMARK.md, I ran a few forward passes on different ONNX exported networks here,  you can see how much % the sigmoids in the swish and se use compared to say a MobileNetV3 that uses hard-swish / hard-sigmoid and doesn't have SE every block.

I've converted the EfficientNet-Lite models, once I've verified them I'll add... they use ReLU6 and no SE so will have lower latency.

**Comment by rwightman** [comment]
I don't really have a great solution for this, I don't want to duplicate code and push this through down to individual model creation helpers and entrypt fns, I have added support in create_model factory but not a good way of calling that via the hub interface. Not sure if I have any other brilliant ideas....
