### ISSUE TITLE
Compound scaling differs from paper

### ISSUE THREAD

**Issue by theDweeb** [rwightman/gen-efficientnet-pytorch#40]
Bringing this issue over from: https://github.com/tensorflow/tpu/issues/738

I am also confused. The starting value for the gamma coefficient (resolution scaling) is 1.15 and the baseline image resolution is 224x224. So it makes sense that 1.15<sup>0</sup> = 1 would be the scaling factor for B0 as 224x1 = 224. EfficientNetB1 would therefore be 1.15<sup>1</sup> = 1.15 and make the resolution for B1 224x1.15 = 257.6, but in the code it shows the B1 resolution is 240, and B2 is 260. I am also confused with the other coefficients as in the code it has:

params_dict = {
#### (width_coefficient, depth_coefficient, resolution, dropout_rate)
'efficientnet-b0': (1.0, 1.0, 224, 0.2),
'efficientnet-b1': (1.0, 1.1, 240, 0.2),
'efficientnet-b2': (1.1, 1.2, 260, 0.3),
'efficientnet-b3': (1.2, 1.4, 300, 0.3),
'efficientnet-b4': (1.4, 1.8, 380, 0.4),
'efficientnet-b5': (1.6, 2.2, 456, 0.4),
'efficientnet-b6': (1.8, 2.6, 528, 0.5),
'efficientnet-b7': (2.0, 3.1, 600, 0.5),
'efficientnet-b8': (2.2, 3.6, 672, 0.5),
'efficientnet-l2': (4.3, 5.3, 800, 0.5),
}

why is β (width) coefficient for B1 = 1.0? Shouldn't it be 1.1<sup>1</sup> = 1.1? And α (depth) coefficient is 1.1 when in the paper it has α as = 1.2.

Just hoping someone in this community could enlighten me

**Comment by rwightman** [comment]
It matches the official impl, which is matches the paper 'in spirit) (there is a lot of rounding/floor/ceil/wiggle/whatever you want to call it). Either way, doesn't matter too much, it's a rough guide for the scaling and looks nice in a paper :)

You aren't the only one with this question, https://github.com/tensorflow/tpu/issues/390. ... and https://forums.fast.ai/t/efficientnet/46978/122
