### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by badcook** [rwightman/gen-efficientnet-pytorch#43]
When run python3 onnx_export.py --model tf_efficientnet_b6_ns ./tf_efficientnet_b6_ns.onnx, I got this error: 
==> Loading and checking exported model from './tf_efficientnet_b6_ns.onnx'
Segmentation fault (core dumped)
how to fix this?

**Comment by rwightman** [comment]
@badcook I've no idea, pytorch and onnx both seem to change and break things with respect to ONNX export on pretty much every release and I can't keep on top of it. If you post the specific versions of ONNX and PyTorch you are using someone else may have a solution, or you can try different combinations of versions...

**Comment by badcook** [comment]
thank you so much, I haved solved this by import onnx before import torch
