### ISSUE TITLE
Importing Tensorflow checkpoints

### ISSUE THREAD

**Issue by kecsap** [rwightman/gen-efficientnet-pytorch#59]
Can you complement the README.md with exact instructions on how to import Tensorflow checkpoints of EfficientNet models? I train EfficientNetB0-B4 models on TPUs now and it would be nice to import into your framework for evaluation. I love pytorch-image-models, it is very handy and I would like to compare the shipped tf_efficientnet_bX models with my new models.

Thanks!

**Comment by rwightman** [comment]
@kecsap there is no conversion here, just the official converted weights, the conversion code is a mess that I've hacked to bits for various versions of the models that often have differing patterns in the underlying weight (graph) naming.  I have no plans on releasing it.

**Comment by kecsap** [comment]
Ok
