### ISSUE TITLE
how to get the validate dataset?

### ISSUE THREAD

**Issue by ILTShade** [rwightman/gen-efficientnet-pytorch#8]
what is the validate dataset and how to organize the dir path tree?

**Comment by rwightman** [comment]
The validation dateset for posted results with pretrained weights is the standare ImageNet-1k validation at http://www.image-net.org/challenges/LSVRC/2011/downloads

You can use the smaller https://github.com/modestyachts/ImageNetV2 set for validation as well that uses newer images sampled in a similar manner with the same classes.

The included data loader is like the PyTorch ImageFolder dataset with a few extra features, it works with any image classification dataset where there is one folder per class

You can use these models like torchvision ones with any other training or validation code and datasets as well by using the model_factory.create_model or torch.hub api to instantiate the models. Just make sure you match the appropriate input image sizes and crop ratios if you expect the performance of the pretrained weights to remain as posted.
